# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39050b368983d026ceb2b8caf107d18b61c9a4ee4c0b5cbc0153eb76be4b09140c04e3522ca1734b80d674a46ece8e1999e8eac234b303af1c18b2f1dfb6e97

test:
  secret_key_base: 67daaea0015dfe5fa9a585093d95bd80b7cb70ada9bdaebb64e23af8a8df93e1d54149726d2ccf93db6e536edeb1e4c7027cf522810751ecfaefcf6a5ece221d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
